-- =====================================================================
-- PROJECT HUB 2.0 - Supabase 전체 초기화/업그레이드 SQL
-- Supabase Dashboard > SQL Editor에서 실행
--
-- 포함 기능
-- 1. 직원 회원가입 프로필
-- 2. 관리자 승인
-- 3. 관리자/일반 사용자 역할
-- 4. 부서별 게시판 읽기/쓰기 권한
-- 5. 5개 게시판
-- 6. 공지 상단고정
-- 7. 게시글 수정/삭제
-- 8. 댓글
-- 9. 조회수
-- 10. 좋아요
-- 11. 프로젝트 일정
-- 12. Storage 파일/이미지
-- 13. RLS 보안정책
-- =====================================================================


-- ---------------------------------------------------------------------
-- 0) 기본 확장
-- ---------------------------------------------------------------------
create extension if not exists pgcrypto;


-- ---------------------------------------------------------------------
-- 1) Profiles
-- ---------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  department text,
  role text not null default 'member'
    check (role in ('member','admin')),
  approved boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists role text not null default 'member',
  add column if not exists approved boolean not null default false,
  add column if not exists updated_at timestamptz not null default now();

-- 회원가입 시 public.profiles 자동 생성
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, name, department, role, approved)
  values (
    new.id,
    new.raw_user_meta_data ->> 'name',
    new.raw_user_meta_data ->> 'department',
    'member',
    false
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();


-- ---------------------------------------------------------------------
-- 2) 보안 Helper Functions
-- security definer 함수로 RLS 내부의 반복 조회를 단순화
-- ---------------------------------------------------------------------
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
      and p.approved = true
  );
$$;

create or replace function public.is_approved()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.approved = true
  );
$$;

create or replace function public.current_department()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select p.department
  from public.profiles p
  where p.id = auth.uid()
  limit 1;
$$;


-- ---------------------------------------------------------------------
-- 3) 게시판 권한
-- 배열이 빈 경우 전체 승인 직원에게 허용
-- ---------------------------------------------------------------------
create table if not exists public.board_permissions (
  board_type text primary key
    check (board_type in ('notice','project','webzine','files','gallery')),
  read_departments text[] not null default '{}',
  write_departments text[] not null default '{}',
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);

insert into public.board_permissions (board_type)
values ('notice'),('project'),('webzine'),('files'),('gallery')
on conflict (board_type) do nothing;

create or replace function public.can_read_board(p_board_type text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    public.is_admin()
    or (
      public.is_approved()
      and exists (
        select 1
        from public.board_permissions bp
        where bp.board_type = p_board_type
          and (
            cardinality(bp.read_departments) = 0
            or public.current_department() = any(bp.read_departments)
          )
      )
    );
$$;

create or replace function public.can_write_board(p_board_type text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    public.is_admin()
    or (
      public.is_approved()
      and exists (
        select 1
        from public.board_permissions bp
        where bp.board_type = p_board_type
          and (
            cardinality(bp.write_departments) = 0
            or public.current_department() = any(bp.write_departments)
          )
      )
    );
$$;


-- ---------------------------------------------------------------------
-- 4) Posts
-- ---------------------------------------------------------------------
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  board_type text not null
    check (board_type in ('notice','project','webzine','files','gallery')),
  title text not null check (char_length(title) between 1 and 200),
  content text default '',
  author_id uuid not null references public.profiles(id) on delete cascade,
  file_name text,
  file_path text,
  is_pinned boolean not null default false,
  view_count bigint not null default 0 check (view_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.posts
  add column if not exists is_pinned boolean not null default false,
  add column if not exists view_count bigint not null default 0,
  add column if not exists updated_at timestamptz not null default now();

create index if not exists posts_board_created_idx
  on public.posts (board_type, is_pinned desc, created_at desc);
create index if not exists posts_author_idx
  on public.posts (author_id);


-- ---------------------------------------------------------------------
-- 5) Comments
-- ---------------------------------------------------------------------
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists comments_post_idx on public.comments(post_id, created_at);


-- ---------------------------------------------------------------------
-- 6) Likes
-- ---------------------------------------------------------------------
create table if not exists public.post_likes (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create index if not exists post_likes_post_idx on public.post_likes(post_id);


-- ---------------------------------------------------------------------
-- 7) Project Schedules
-- ---------------------------------------------------------------------
create table if not exists public.project_schedules (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 200),
  description text default '',
  department text,
  start_at timestamptz not null,
  end_at timestamptz not null,
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint schedule_time_check check (end_at >= start_at)
);

create index if not exists schedules_start_idx on public.project_schedules(start_at);


-- ---------------------------------------------------------------------
-- 8) updated_at Trigger
-- ---------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

drop trigger if exists set_permissions_updated_at on public.board_permissions;
create trigger set_permissions_updated_at
before update on public.board_permissions
for each row execute procedure public.set_updated_at();

drop trigger if exists set_posts_updated_at on public.posts;
create trigger set_posts_updated_at
before update on public.posts
for each row execute procedure public.set_updated_at();

drop trigger if exists set_comments_updated_at on public.comments;
create trigger set_comments_updated_at
before update on public.comments
for each row execute procedure public.set_updated_at();

drop trigger if exists set_schedules_updated_at on public.project_schedules;
create trigger set_schedules_updated_at
before update on public.project_schedules
for each row execute procedure public.set_updated_at();


-- ---------------------------------------------------------------------
-- 9) 조회수 RPC
-- 승인된 사용자가 볼 수 있는 게시글만 +1
-- ---------------------------------------------------------------------
create or replace function public.increment_post_view(p_post_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_board_type text;
begin
  select board_type into v_board_type
  from public.posts
  where id = p_post_id;

  if v_board_type is null then
    return;
  end if;

  if not public.can_read_board(v_board_type) then
    raise exception 'not authorized';
  end if;

  update public.posts
  set view_count = view_count + 1
  where id = p_post_id;
end;
$$;

revoke all on function public.increment_post_view(bigint) from public;
grant execute on function public.increment_post_view(bigint) to authenticated;


-- ---------------------------------------------------------------------
-- 10) RLS 활성화
-- ---------------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.board_permissions enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.post_likes enable row level security;
alter table public.project_schedules enable row level security;


-- ---------------------------------------------------------------------
-- 11) Profiles Policies
-- ---------------------------------------------------------------------
drop policy if exists "Users read own profile" on public.profiles;
create policy "Users read own profile"
on public.profiles
for select
to authenticated
using (
  id = (select auth.uid())
  or public.is_admin()
  or (public.is_approved() and approved = true)
);

drop policy if exists "Admins manage profiles" on public.profiles;
create policy "Admins manage profiles"
on public.profiles
for update
to authenticated
using (
  public.is_admin()
  or id = (select auth.uid())
)
with check (
  public.is_admin()
  or (
    id = (select auth.uid())
    -- 사용자는 자신의 role/approved를 임의 변경할 수 없어야 함.
    -- 아래 Trigger에서 민감 컬럼을 보호함.
  )
);

-- 일반 사용자의 role/approved 변경 방지
create or replace function public.protect_profile_privileges()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() = old.id and not public.is_admin() then
    new.role := old.role;
    new.approved := old.approved;
  end if;
  return new;
end;
$$;

drop trigger if exists protect_profile_privileges_trigger on public.profiles;
create trigger protect_profile_privileges_trigger
before update on public.profiles
for each row execute procedure public.protect_profile_privileges();


-- ---------------------------------------------------------------------
-- 12) Board Permissions Policies
-- ---------------------------------------------------------------------
drop policy if exists "Approved read board permissions" on public.board_permissions;
create policy "Approved read board permissions"
on public.board_permissions
for select
to authenticated
using (public.is_approved());

drop policy if exists "Admins insert board permissions" on public.board_permissions;
create policy "Admins insert board permissions"
on public.board_permissions
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins update board permissions" on public.board_permissions;
create policy "Admins update board permissions"
on public.board_permissions
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());


-- ---------------------------------------------------------------------
-- 13) Posts Policies
-- ---------------------------------------------------------------------
drop policy if exists "Authorized users read posts" on public.posts;
create policy "Authorized users read posts"
on public.posts
for select
to authenticated
using (public.can_read_board(board_type));

drop policy if exists "Authorized users create posts" on public.posts;
create policy "Authorized users create posts"
on public.posts
for insert
to authenticated
with check (
  public.can_write_board(board_type)
  and author_id = (select auth.uid())
  and (
    is_pinned = false
    or (public.is_admin() and board_type = 'notice')
  )
);

drop policy if exists "Authors or admins update posts" on public.posts;
create policy "Authors or admins update posts"
on public.posts
for update
to authenticated
using (
  public.can_write_board(board_type)
  and (
    author_id = (select auth.uid())
    or public.is_admin()
  )
)
with check (
  public.can_write_board(board_type)
  and (
    author_id = (select auth.uid())
    or public.is_admin()
  )
);

-- 일반 작성자가 is_pinned을 바꾸지 못하도록 Trigger
create or replace function public.protect_post_admin_fields()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    new.is_pinned := old.is_pinned;
    new.view_count := old.view_count;
    new.author_id := old.author_id;
    new.board_type := old.board_type;
  end if;
  return new;
end;
$$;

drop trigger if exists protect_post_admin_fields_trigger on public.posts;
create trigger protect_post_admin_fields_trigger
before update on public.posts
for each row execute procedure public.protect_post_admin_fields();

drop policy if exists "Authors or admins delete posts" on public.posts;
create policy "Authors or admins delete posts"
on public.posts
for delete
to authenticated
using (
  author_id = (select auth.uid())
  or public.is_admin()
);


-- ---------------------------------------------------------------------
-- 14) Comments Policies
-- ---------------------------------------------------------------------
drop policy if exists "Authorized users read comments" on public.comments;
create policy "Authorized users read comments"
on public.comments
for select
to authenticated
using (
  exists (
    select 1 from public.posts p
    where p.id = comments.post_id
      and public.can_read_board(p.board_type)
  )
);

drop policy if exists "Approved users create comments" on public.comments;
create policy "Approved users create comments"
on public.comments
for insert
to authenticated
with check (
  public.is_approved()
  and user_id = (select auth.uid())
  and exists (
    select 1 from public.posts p
    where p.id = comments.post_id
      and public.can_read_board(p.board_type)
  )
);

drop policy if exists "Authors or admins update comments" on public.comments;
create policy "Authors or admins update comments"
on public.comments
for update
to authenticated
using (user_id = (select auth.uid()) or public.is_admin())
with check (user_id = (select auth.uid()) or public.is_admin());

drop policy if exists "Authors or admins delete comments" on public.comments;
create policy "Authors or admins delete comments"
on public.comments
for delete
to authenticated
using (user_id = (select auth.uid()) or public.is_admin());


-- ---------------------------------------------------------------------
-- 15) Likes Policies
-- ---------------------------------------------------------------------
drop policy if exists "Authorized users read likes" on public.post_likes;
create policy "Authorized users read likes"
on public.post_likes
for select
to authenticated
using (
  exists (
    select 1 from public.posts p
    where p.id = post_likes.post_id
      and public.can_read_board(p.board_type)
  )
);

drop policy if exists "Approved users create own likes" on public.post_likes;
create policy "Approved users create own likes"
on public.post_likes
for insert
to authenticated
with check (
  public.is_approved()
  and user_id = (select auth.uid())
  and exists (
    select 1 from public.posts p
    where p.id = post_likes.post_id
      and public.can_read_board(p.board_type)
  )
);

drop policy if exists "Users delete own likes" on public.post_likes;
create policy "Users delete own likes"
on public.post_likes
for delete
to authenticated
using (user_id = (select auth.uid()) or public.is_admin());


-- ---------------------------------------------------------------------
-- 16) Schedule Policies
-- 승인된 직원 전체 읽기, ADMIN만 쓰기
-- ---------------------------------------------------------------------
drop policy if exists "Approved users read schedules" on public.project_schedules;
create policy "Approved users read schedules"
on public.project_schedules
for select
to authenticated
using (public.is_approved());

drop policy if exists "Admins create schedules" on public.project_schedules;
create policy "Admins create schedules"
on public.project_schedules
for insert
to authenticated
with check (public.is_admin() and created_by = (select auth.uid()));

drop policy if exists "Admins update schedules" on public.project_schedules;
create policy "Admins update schedules"
on public.project_schedules
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins delete schedules" on public.project_schedules;
create policy "Admins delete schedules"
on public.project_schedules
for delete
to authenticated
using (public.is_admin());


-- ---------------------------------------------------------------------
-- 17) Storage
-- Private bucket
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('project-files','project-files',false)
on conflict (id) do update set public = false;

-- 기존 정책 삭제
drop policy if exists "Approved users read project files" on storage.objects;
drop policy if exists "Users upload to own folder" on storage.objects;
drop policy if exists "Users update own files" on storage.objects;
drop policy if exists "Users delete own files" on storage.objects;

-- 승인된 직원 파일 조회
create policy "Approved users read project files"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'project-files'
  and public.is_approved()
);

-- 본인 UUID 폴더에만 업로드
create policy "Users upload to own folder"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'project-files'
  and public.is_approved()
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

create policy "Users update own files"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'project-files'
  and public.is_approved()
  and (
    (storage.foldername(name))[1] = (select auth.uid()::text)
    or public.is_admin()
  )
)
with check (
  bucket_id = 'project-files'
  and public.is_approved()
);

create policy "Users delete own files"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'project-files'
  and public.is_approved()
  and (
    (storage.foldername(name))[1] = (select auth.uid()::text)
    or public.is_admin()
  )
);


-- ---------------------------------------------------------------------
-- 18) 첫 관리자 지정
--
-- 중요:
-- 1) 먼저 웹에서 본인 이메일로 회원가입
-- 2) 이메일 인증
-- 3) 아래 YOUR_ADMIN_EMAIL 부분을 실제 이메일로 바꿔 딱 한 번 실행
-- ---------------------------------------------------------------------
-- update public.profiles
-- set role = 'admin',
--     approved = true
-- where id = (
--   select id
--   from auth.users
--   where email = 'YOUR_ADMIN_EMAIL@company.com'
-- );


-- ---------------------------------------------------------------------
-- 19) 기존 1차 버전 사용자가 있는 경우
-- 필요하면 기존 회원을 일괄 승인하는 일회성 명령
-- 운영 전 검토 후 직접 실행
-- ---------------------------------------------------------------------
-- update public.profiles
-- set approved = true
-- where approved = false;


-- ---------------------------------------------------------------------
-- 20) 점검용 SQL
-- ---------------------------------------------------------------------
-- select id, name, department, role, approved, created_at
-- from public.profiles
-- order by created_at desc;
--
-- select * from public.board_permissions order by board_type;
--
-- select board_type, count(*) from public.posts group by board_type;
